# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Short But Great Stories"
description: > # this means to ignore newlines until "email:"
   Projeto de escrita independente, mas sou dependente de alma da escrita.

email: viniciussouza31122002@gmail.com
#blog logo
logo: "/assets/images/SBGS_logo2_wb.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image_3.png"

name: 'Vinicius de Souza Marcon'
author: 'Vinicius de Souza Marcon'
author_image: "/assets/images/profile_picture.jpeg"

paginate:	5

url: "http://vsmarcon.github.io" # the base hostname & protocol for your site
baseurl: "/ShortButGreatStories"
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	instagram
    url:	https://instagram.com/_marc0n
    desc: Siga-me no Instagram
    # share_url: http://twitter.com/share
    # share_title: ?text=
    # share_link: "&amp;url="
  - icon:	mug-hot
    url:	https://www.buymeacoffee.com/sbgstories/
    desc: Suporte a p√°gina
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
